@isTest(SeeAllData=true)
public class RHX_TEST_OpportunityContactRole {
	static testMethod void RHX_Testmethod() {
        List<sObject> sourceList = [SELECT Id 
			FROM OpportunityContactRole LIMIT 1];
        if(sourceList.size() == 0) {
            sourceList.add(
                    new OpportunityContactRole()
            );
        }
    	rh2.ParentUtil.UpsertRollupTestRecords( sourceList );
    }
}